'use strict';
const $=id=>document.getElementById(id);
const EMB={toi:'assets/toi.png',spesa:'assets/spesa.png',vg:'assets/vg.png',logo:'assets/logo.png'};
const DEFAULT_APPS=[
{id:'toi',name:'Turni Operai Italia',version:'0.3.0',description:'Gestisci i tuoi turni di lavoro in modo semplice',category:'Produttività',status:'In test',featured:true,update:'Nuove personalizzazioni dei turni',icon:EMB.toi,updateKind:'Novità',playUrl:'',apkUrl:''},
{id:'spesa',name:'SpesaScan',version:'0.1',description:'Scansiona, organizza e risparmia sulla spesa',category:'Utility',status:'In arrivo',featured:true,update:'Riconoscimento prodotti migliorato',icon:EMB.spesa,updateKind:'Aggiornamento',playUrl:'',apkUrl:''},
{id:'vg',name:'Gestionale V&G',version:'0.7.1',description:'La soluzione completa per la tua azienda',category:'Produttività',status:'Disponibile',featured:true,update:'Nuove funzioni e miglioramenti',icon:EMB.vg,updateKind:'Nuova versione',playUrl:'',apkUrl:''}
];
const SITE_DEFAULT={title:'SimplexApp',tagline:'Le tue app, in un unico posto',hero:'Organizza, scopri e utilizza le tue app preferite in un unico posto.'};
const keys={apps:'simplex_apps_v31',site:'simplex_site_v31',favs:'simplex_favs_v31'};
let memory={},storageWarning=false,currentCat='',onlyFav=false,editingIcon='',showAllUpdates=false;
function read(k,fallback){try{const val=JSON.parse(localStorage.getItem(k));return val??fallback}catch{return memory[k]??fallback}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));memory[k]=v;return true}catch{memory[k]=v;storageWarning=true;toast('Salvataggio permanente non disponibile. Esporta un backup JSON.');return false}}
function getApps(){const a=read(keys.apps,DEFAULT_APPS);return Array.isArray(a)?a:DEFAULT_APPS}
function setApps(a){write(keys.apps,a);render();renderAdminList()}
function getSite(){return {...SITE_DEFAULT,...read(keys.site,{})}}
function getFavs(){const f=read(keys.favs,[]);return Array.isArray(f)?f:[]}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeURL(s){if(typeof s!=='string'||!s.trim())return '';try{const u=new URL(s,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function safeIcon(s){if(/^data:image\/(png|jpeg|webp|gif);base64,/i.test(s||''))return s;return safeURL(s||EMB.logo)||EMB.logo}
let toastTimer;
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),3500)}
function action(a){const href=safeURL(a.playUrl)||safeURL(a.apkUrl);return href?`<a class="btn" href="${esc(href)}" target="_blank" rel="noopener noreferrer"><span class="external" aria-hidden="true">↗</span>Apri</a>`:`<button class="btn" data-detail="${esc(a.id)}"><span class="external" aria-hidden="true">↗</span>Scopri</button>`}
function card(a,featured=false){const f=getFavs().includes(a.id);return `<article class="app-card tone-${esc(a.id)}"><div class="card-top"><img class="app-icon" src="${esc(safeIcon(a.icon))}" alt="Icona ${esc(a.name)}"><div class="card-content"><h3>${esc(a.name)}</h3><p>${esc(a.description)}</p>${featured?`<div class="meta"><span class="version">v${esc(a.version||'—')}</span><span class="status">${esc(a.status||'Disponibile')}</span></div>`:''}</div></div><button class="fav" data-fav="${esc(a.id)}" aria-label="${f?'Rimuovi':'Aggiungi'} ${esc(a.name)} ${f?'dai':'ai'} preferiti" aria-pressed="${f}"><img src="assets/${f?'heart':'heart-outline'}.png" alt=""></button>${!featured?`<div class="meta"><span class="status">${esc(a.status||'Disponibile')}</span></div>`:''}<div class="actions">${!featured?`<span class="version">v${esc(a.version||'—')}</span>`:''}${action(a)}</div></article>`}
function render(){const s=getSite();if(s.title==='SimplexApp')$('siteTitle').innerHTML='Simplex<em>App</em>';else $('siteTitle').textContent=s.title;$('siteTagline').textContent=s.tagline;$('heroText').textContent=s.hero;document.title=s.title;
 const a=getApps();$('featured').innerHTML=a.filter(x=>x.featured).map(x=>card(x,true)).join('')||'<p class="empty">Nessuna app in evidenza.</p>';
 const q=$('search').value.trim().toLocaleLowerCase('it');const list=a.filter(x=>(!currentCat||x.category===currentCat)&&(!onlyFav||getFavs().includes(x.id))&&(!q||[x.name,x.description,x.category].join(' ').toLocaleLowerCase('it').includes(q)));
 $('catalogGrid').innerHTML=list.map(x=>card(x)).join('')||'<p class="empty">'+(onlyFav?'Nessun preferito: tocca il cuore su un’app.':'Nessuna app trovata con questi filtri.')+'</p>';
 $('catalogTitle').textContent=onlyFav?'Le tue app preferite':'Catalogo app';$('filterBar').classList.toggle('hidden',!currentCat&&!onlyFav&&!q);$('filterText').textContent=[currentCat,onlyFav?'Preferiti':'',`${list.length} app`].filter(Boolean).join(' · ');
 const updates=a.filter(x=>x.update);$('updates').innerHTML=(showAllUpdates?updates:updates.slice(0,3)).map(x=>`<article class="update"><img src="${esc(safeIcon(x.icon))}" alt=""><div class="update-body"><div class="update-title"><b>${esc(x.name)}</b><span class="badge ${x.updateKind==='Aggiornamento'?'green':x.updateKind==='Nuova versione'?'purple':''}">${esc(x.updateKind||'Novità')}</span></div><span class="meta">v${esc(x.version||'—')}</span><p>${esc(x.update)}</p></div></article>`).join('')||'<p class="empty">Nessun aggiornamento.</p>';
 document.querySelectorAll('[data-cat]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cat===currentCat)));
 document.querySelectorAll('img').forEach(img=>img.onerror=()=>{img.onerror=null;img.src=EMB.logo});
}
function setNav(view){document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
function navigate(view){if(view==='admin'){showAdmin();return}hideAdmin(false);setNav(view);onlyFav=view==='preferiti';currentCat='';$('search').value='';render();if(view==='home')window.scrollTo({top:0,behavior:'smooth'});else $('catalogo').scrollIntoView({behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){navigate(b.dataset.view);return}if(b.dataset.cat){hideAdmin(false);currentCat=currentCat===b.dataset.cat?'':b.dataset.cat;onlyFav=false;$('search').value='';setNav('catalogo');render();$('catalogo').scrollIntoView({behavior:'smooth'})}if(b.dataset.fav){const f=getFavs();write(keys.favs,f.includes(b.dataset.fav)?f.filter(x=>x!==b.dataset.fav):[...f,b.dataset.fav]);render()}if(b.dataset.detail)showDetail(b.dataset.detail)});
$('search').oninput=render;$('clearFilters').onclick=()=>{currentCat='';onlyFav=false;$('search').value='';setNav('catalogo');render()};$('viewUpdates').onclick=()=>{showAllUpdates=true;render();$('novita').scrollIntoView({behavior:'smooth'})};
function showDetail(id){const a=getApps().find(x=>x.id===id);if(!a)return;$('detailContent').innerHTML=`<img class="app-icon" src="${esc(safeIcon(a.icon))}" alt=""><h2>${esc(a.name)}</h2><p>${esc(a.description)}</p><p>Versione ${esc(a.version)} · ${esc(a.category)}<br>${esc(a.status)}</p><p>${esc(a.update||'')}</p>${safeURL(a.playUrl)?`<a class="btn" href="${esc(safeURL(a.playUrl))}" target="_blank" rel="noopener">Google Play</a>`:''}${safeURL(a.apkUrl)?`<p><a class="btn" href="${esc(safeURL(a.apkUrl))}" target="_blank" rel="noopener">Scarica APK</a></p>`:''}${!safeURL(a.playUrl)&&!safeURL(a.apkUrl)?'<p>Il download non è ancora disponibile.</p>':''}`;$('appDialog').showModal()}
$('closeDialog').onclick=()=>$('appDialog').close();$('appDialog').onclick=e=>{if(e.target===$('appDialog'))$('appDialog').close()};
function showAdmin(){$('homeView').classList.add('hidden');$('adminView').classList.remove('hidden');loadAdmin();setNav('admin');window.scrollTo(0,0)}
function hideAdmin(scroll=true){$('adminView').classList.add('hidden');$('homeView').classList.remove('hidden');if(scroll){setNav('home');render();window.scrollTo(0,0)}}
$('openAdmin').onclick=showAdmin;$('closeAdmin').onclick=()=>hideAdmin();
function loadAdmin(){const s=getSite();$('sTitle').value=s.title;$('sTag').value=s.tagline;$('sHero').value=s.hero;renderAdminList()}
$('saveSite').onclick=()=>{const ok=write(keys.site,{title:$('sTitle').value.trim()||'SimplexApp',tagline:$('sTag').value.trim(),hero:$('sHero').value.trim()});render();if(ok)toast('Impostazioni salvate')};
function resetForm(){['appId','appName','appVersion','appDesc','appUpdate','appPlay','appApk','appIcon','appIconFile'].forEach(id=>$(id).value='');$('appCat').value='Produttività';$('appStatus').value='Disponibile';$('appUpdateKind').value='Novità';$('appFeatured').checked=false;editingIcon=''}
$('newApp').onclick=resetForm;
function editApp(x){$('appId').value=x.id;$('appName').value=x.name;$('appVersion').value=x.version||'';$('appDesc').value=x.description||'';$('appCat').value=x.category||'Utility';$('appStatus').value=x.status||'Disponibile';$('appUpdate').value=x.update||'';$('appUpdateKind').value=x.updateKind||'Novità';$('appPlay').value=x.playUrl||'';$('appApk').value=x.apkUrl||'';editingIcon=x.icon||EMB.logo;$('appIcon').value=(x.icon||'').startsWith('data:')?'':x.icon||'';$('appIconFile').value='';$('appFeatured').checked=!!x.featured;$('appName').scrollIntoView({behavior:'smooth',block:'center'})}
async function imageFile(file){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Usa PNG, JPEG, WebP o GIF.');if(file.size>8*1024*1024)throw Error('Immagine troppo grande (massimo 8 MB).');const bitmap=await createImageBitmap(file);const size=Math.min(1,256/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*size);canvas.height=Math.round(bitmap.height*size);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/png')}
$('saveApp').onclick=async()=>{if(!$('appName').value.trim()){$('appName').focus();toast('Inserisci il nome dell’app');return}for(const id of ['appPlay','appApk'])if($(id).value.trim()&&!safeURL($(id).value.trim()))return toast('Inserisci un link HTTPS o HTTP valido');try{const a=getApps();const item={id:$('appId').value||'app_'+Date.now(),name:$('appName').value.trim(),version:$('appVersion').value.trim(),description:$('appDesc').value.trim(),category:$('appCat').value,status:$('appStatus').value,update:$('appUpdate').value.trim(),updateKind:$('appUpdateKind').value,playUrl:$('appPlay').value.trim(),apkUrl:$('appApk').value.trim(),icon:$('appIconFile').files[0]?await imageFile($('appIconFile').files[0]):$('appIcon').value.trim()||editingIcon||EMB.logo,featured:$('appFeatured').checked};const i=a.findIndex(x=>x.id===item.id);if(i>=0)a[i]=item;else a.push(item);setApps(a);resetForm();if(!storageWarning)toast('App salvata: la home è aggiornata')}catch(e){toast(e.message||'Impossibile salvare l’immagine')}};
function renderAdminList(){const list=$('adminList');list.innerHTML='';getApps().forEach(x=>{const d=document.createElement('div');d.className='admin-item';d.innerHTML=`<div><strong>${esc(x.name)}</strong><small>${esc(x.category)} · ${esc(x.status)} · v${esc(x.version)}</small></div><div><button class="secondary e">Modifica</button> <button class="danger d">Elimina</button></div>`;d.querySelector('.e').onclick=()=>editApp(x);d.querySelector('.d').onclick=()=>{if(confirm('Eliminare '+x.name+'?')){setApps(getApps().filter(a=>a.id!==x.id));write(keys.favs,getFavs().filter(id=>id!==x.id));toast('App eliminata')}};list.appendChild(d)})}
$('exportData').onclick=()=>{const data={schemaVersion:1,site:getSite(),apps:getApps()};const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.download='simplex-catalogo.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),5000)};
function normalizeApps(a){if(!Array.isArray(a))throw Error('Il catalogo deve contenere un elenco di app.');const ids=new Set();return a.map(x=>{if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.name!=='string'||!x.name.trim())throw Error('Scheda non valida o ID duplicato.');ids.add(x.id);const y={id:x.id,name:x.name,featured:!!x.featured};for(const k of ['version','description','status','update','updateKind','playUrl','apkUrl','icon'])y[k]=typeof x[k]==='string'?x[k]:'';y.category=['Produttività','Comunicazione','Utility','Giochi'].includes(x.category)?x.category:'Utility';return y})}
$('importData').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());const apps=normalizeApps(Array.isArray(data)?data:data.apps);if(!confirm('Sostituire il catalogo con '+apps.length+' app?'))return;setApps(apps);if(data.site){const site={};for(const k of ['title','tagline','hero'])if(typeof data.site[k]==='string')site[k]=data.site[k];write(keys.site,{...SITE_DEFAULT,...site})}loadAdmin();render();toast('Catalogo importato')}catch(err){toast('Importazione fallita: '+err.message)}finally{e.target.value=''}};
async function boot(){try{const [apps,site]=await Promise.all([fetch('data/apps.json',{cache:'no-cache'}).then(r=>r.ok?r.json():null),fetch('data/site.json',{cache:'no-cache'}).then(r=>r.ok?r.json():null)]);if(!read(keys.apps,null)&&apps){const valid=normalizeApps(apps);memory[keys.apps]=valid;DEFAULT_APPS.splice(0,DEFAULT_APPS.length,...valid)}if(!read(keys.site,null)&&site)Object.assign(SITE_DEFAULT,site)}catch{}render();if('serviceWorker'in navigator&&['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>toast('Modalità offline non disponibile su questo indirizzo'))}
render();boot();
