'use strict';
const $=id=>document.getElementById(id);
const EMB={toi:'assets/toi.png',spesa:'assets/spesa.png',vg:'assets/vg.png',logo:'assets/simplexapp-icon.svg'};
const DEFAULT_APPS=[
{id:'toi',name:'Turni Operai Italia',version:'0.3.0',description:'Gestisci i tuoi turni di lavoro in modo semplice',category:'Produttività',status:'In test',featured:true,update:'Nuove personalizzazioni dei turni',icon:EMB.toi,updateKind:'Novità',playUrl:'',apkUrl:''},
{id:'spesa',name:'SpesaScan',version:'0.1',description:'Scansiona, organizza e risparmia sulla spesa',category:'Utility',status:'In arrivo',featured:true,update:'Riconoscimento prodotti migliorato',icon:EMB.spesa,updateKind:'Aggiornamento',playUrl:'',apkUrl:''},
{id:'vg',name:'Gestionale V&G',version:'0.7.1',description:'La soluzione completa per la tua azienda',category:'Produttività',status:'Disponibile',featured:true,update:'Nuove funzioni e miglioramenti',icon:EMB.vg,updateKind:'Nuova versione',playUrl:'',apkUrl:''}
];
const DEFAULT_CATEGORIES=['Produttività','Comunicazione','Utility','Giochi'];
const SITE_DEFAULT={title:'SimplexApp',tagline:'Le tue app, in un unico posto',hero:'Organizza, scopri e utilizza le tue app preferite in un unico posto.',theme:'premium',categories:DEFAULT_CATEGORIES};
const keys={apps:'simplex_cloud_apps_v1',site:'simplex_cloud_site_v1',favs:'simplex_favs_v31'};
let memory={},storageWarning=false,currentCat='',onlyFav=false,editingIcon='',showAllUpdates=false;
function read(k,fallback){try{const val=JSON.parse(localStorage.getItem(k));return val??fallback}catch{return memory[k]??fallback}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));memory[k]=v;return true}catch{memory[k]=v;storageWarning=true;toast('Salvataggio permanente non disponibile. Esporta un backup JSON.');return false}}
function getApps(){const a=read(keys.apps,DEFAULT_APPS);return Array.isArray(a)?a:DEFAULT_APPS}
function getPublicApps(){return getApps().filter(a=>a.visiblePublic!==false)}
function setApps(a){write(keys.apps,a);render();renderAdminList();if(location.hash.startsWith('#app/'))renderDetail(detailId())}
function getSite(){return {...SITE_DEFAULT,...read(keys.site,{})}}
function getCategories(){const s=getSite(),base=Array.isArray(s.categories)&&s.categories.length?s.categories:DEFAULT_CATEGORIES;return [...new Set([...base,...getApps().map(a=>a.category).filter(Boolean)])]}
function syncCategorySelect(selected){const sel=$('appCat');if(!sel)return;const value=selected||sel.value||getCategories()[0]||'Utility';sel.innerHTML=getCategories().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(!getCategories().includes(value)){const o=document.createElement('option');o.value=value;o.textContent=value;sel.appendChild(o)}sel.value=value}
function getFavs(){const f=read(keys.favs,[]);return Array.isArray(f)?f:[]}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeURL(s){if(typeof s!=='string'||!s.trim())return '';try{const u=new URL(s,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function safeIcon(s){if(/^data:image\/(png|jpeg|webp|gif);base64,/i.test(s||''))return s;return safeURL(s||EMB.logo)||EMB.logo}
let toastTimer;
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),3500)}
function action(a){return `<a class="btn card-link" href="#app/${encodeURIComponent(a.id)}" aria-label="Scopri ${esc(a.name)}"><span class="external" aria-hidden="true">↗</span>Scopri</a>`}
function card(a,featured=false){const f=getFavs().includes(a.id);return `<article class="app-card tone-${esc(a.id)}"><div class="card-top"><img class="app-icon" src="${esc(safeIcon(a.icon))}" alt="Icona ${esc(a.name)}"><div class="card-content"><h3>${esc(a.name)}</h3><p>${esc(a.description)}</p>${featured?`<div class="meta"><span class="version">v${esc(a.version||'—')}</span><span class="status">${esc(a.status||'Disponibile')}</span></div>`:''}</div></div><button class="fav" data-fav="${esc(a.id)}" aria-label="${f?'Rimuovi':'Aggiungi'} ${esc(a.name)} ${f?'dai':'ai'} preferiti" aria-pressed="${f}"><img src="assets/${f?'heart':'heart-outline'}.png" alt=""></button>${!featured?`<div class="meta"><span class="status">${esc(a.status||'Disponibile')}</span></div>`:''}<div class="actions">${!featured?`<span class="version">v${esc(a.version||'—')}</span>`:''}${action(a)}</div><button class="share-app" data-share="${esc(a.id)}" aria-label="Condividi ${esc(a.name)}">Condividi</button></article>`}
function render(){if(document.activeElement!==$('heroSearch'))$('heroSearch').value=$('search').value;const s=getSite();document.documentElement.dataset.theme=(['classic','premium'].includes(new URLSearchParams(location.search).get('theme'))?new URLSearchParams(location.search).get('theme'):s.theme==='classic'?'classic':'premium');if(s.title==='SimplexApp')$('siteTitle').innerHTML='Simplex<em>App</em>';else $('siteTitle').textContent=s.title;$('siteTagline').textContent=s.tagline;$('heroText').textContent=s.hero;document.title=s.title;
 const a=getPublicApps();renderFeatured(a);
 const q=$('search').value.trim().toLocaleLowerCase('it');const list=a.filter(x=>(!currentCat||x.category===currentCat)&&(!onlyFav||getFavs().includes(x.id))&&(!q||[x.name,x.description,x.category].join(' ').toLocaleLowerCase('it').includes(q)));
 $('catalogGrid').innerHTML=list.map(x=>card(x)).join('')||'<p class="empty">'+(onlyFav?'Nessun preferito: tocca il cuore su un’app.':'Nessuna app trovata con questi filtri.')+'</p>';
 $('catalogTitle').textContent=onlyFav?'Le tue app preferite':'Catalogo app';$('filterBar').classList.toggle('hidden',!currentCat&&!onlyFav&&!q);$('filterText').textContent=[currentCat,onlyFav?'Preferiti':'',`${list.length} app`].filter(Boolean).join(' · ');
 const updates=a.filter(x=>x.update);$('updates').innerHTML=(showAllUpdates?updates:updates.slice(0,3)).map(x=>`<article class="update"><a class="update-link" href="#app/${encodeURIComponent(x.id)}" aria-label="Dettagli di ${esc(x.name)}"></a><img src="${esc(safeIcon(x.icon))}" alt=""><div class="update-body"><div class="update-title"><b>${esc(x.name)}</b><span class="badge ${x.updateKind==='Aggiornamento'?'green':x.updateKind==='Nuova versione'?'purple':''}">${esc(x.updateKind||'Novità')}</span></div><span class="meta">v${esc(x.version||'—')}</span><p>${esc(x.update)}</p></div></article>`).join('')||'<p class="empty">Nessun aggiornamento.</p>';
 document.querySelectorAll('[data-cat]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cat===currentCat)));
 document.querySelectorAll('img').forEach(img=>img.onerror=()=>{img.onerror=null;img.src=EMB.logo});
}
function renderFeatured(apps=getApps()){const pool=[...apps.filter(x=>x.featured),...apps.filter(x=>!x.featured)];if(!pool.length){$('featured').innerHTML='<p class="empty">Nessuna app in evidenza.</p>';return}const count=Math.min(3,pool.length),start=Math.floor(Date.now()/12000)%pool.length,chosen=Array.from({length:count},(_,i)=>pool[(start+i)%pool.length]);$('featured').innerHTML=chosen.map(x=>card(x,true)).join('')}
setInterval(()=>{if(!$('homeView').classList.contains('hidden'))renderFeatured()},12000);
function setNav(view){document.querySelectorAll('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
let activeScreen='home';
function snapshotScreen(){if(!history.state?.simplexInitialized)return;history.replaceState({...history.state,cat:currentCat,onlyFav,search:$('search').value,scroll:window.scrollY},'',location.href)}
function applyScreen(view,state={}){activeScreen=view;if(view==='admin'){showAdmin(true);return}hideAdmin(false);$('detailView').classList.add('hidden');setNav(view);onlyFav=state.onlyFav??view==='preferiti';currentCat=state.cat||'';$('search').value=state.search||'';render();if(typeof state.scroll==='number')window.scrollTo({top:state.scroll,behavior:'instant'});else if(view==='home')window.scrollTo({top:0,behavior:'smooth'});else $('catalogo').scrollIntoView({behavior:'smooth'})}
function navigate(view,state={}){snapshotScreen();history.pushState({simplexInitialized:true,simplexScreen:view,...state},'',location.pathname+location.search+'#'+view);applyScreen(view,state)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.share){shareApp(b.dataset.share);return}if(b.dataset.view){if(b.dataset.view!==activeScreen)navigate(b.dataset.view);else applyScreen(b.dataset.view);return}if(b.dataset.cat){navigate('catalogo',{cat:currentCat===b.dataset.cat?'':b.dataset.cat,onlyFav:false,search:''});return}if(b.dataset.fav){const f=getFavs();write(keys.favs,f.includes(b.dataset.fav)?f.filter(x=>x!==b.dataset.fav):[...f,b.dataset.fav]);render();if(location.hash.startsWith('#app/'))renderDetail(detailId())}if(b.dataset.detail)showDetail(b.dataset.detail)});
$('search').oninput=render;$('heroSearch').oninput=()=>{$('search').value=$('heroSearch').value;render()};$('heroSearch').onkeydown=e=>{if(e.key==='Enter'){$('catalogo').scrollIntoView({behavior:'smooth'});$('heroSearch').blur()}};$('clearFilters').onclick=()=>{currentCat='';onlyFav=false;$('search').value='';setNav('catalogo');render()};$('viewUpdates').onclick=()=>{showAllUpdates=true;render();$('novita').scrollIntoView({behavior:'smooth'})};
let detailReturnScroll=0,detailInternal=false;
function renderDetail(id){
 const a=getPublicApps().find(x=>x.id===id);if(a)document.title=a.name+' · '+getSite().title;if(!a){$('detailContent').innerHTML='<section class="panel"><h1>App non disponibile</h1><p>Questa scheda non è più nel catalogo.</p></section>';return}
 const shots=Array.isArray(a.screenshots)?a.screenshots.filter(u=>safeURL(u)):[];
 const actions=`${safeURL(a.playUrl)?`<a class="btn" href="${esc(safeURL(a.playUrl))}" target="_blank" rel="noopener noreferrer">Apri su Google Play ↗</a>`:''}${safeURL(a.apkUrl)?`<a class="btn" href="${esc(safeURL(a.apkUrl))}" target="_blank" rel="noopener noreferrer">Scarica APK ↓</a>`:''}<button class="secondary" data-share="${esc(a.id)}">Condividi app</button><button class="detail-fav secondary" data-fav="${esc(a.id)}" aria-pressed="${getFavs().includes(a.id)}">${getFavs().includes(a.id)?'♥ Nei preferiti':'♡ Aggiungi ai preferiti'}</button>`;
 $('detailContent').innerHTML=`<section class="detail-hero tone-${esc(a.id)}"><img class="detail-icon" src="${esc(safeIcon(a.icon))}" alt="Icona ${esc(a.name)}"><div><span class="detail-category">${esc(a.category)}</span><h1 tabindex="-1" id="detailTitle">${esc(a.name)}</h1><p>${esc(a.description)}</p><div class="detail-meta"><span class="version">v${esc(a.version||'—')}</span><span class="version">${esc(a.status||'Disponibile')}</span></div></div></section><section class="panel detail-panel"><h2>Screenshot</h2>${shots.length?`<div class="screenshots">${shots.map((u,i)=>`<button class="screenshot" data-screen="${esc(u)}" aria-label="Ingrandisci screenshot ${i+1} di ${esc(a.name)}"><img src="${esc(u)}" alt="Screenshot ${i+1} di ${esc(a.name)}" loading="lazy"></button>`).join('')}</div><p class="note">Scorri le immagini e toccale per ingrandirle.</p>`:'<p class="note">Gli screenshot non sono ancora stati aggiunti.</p>'}</section><section class="panel detail-panel"><h2>Informazioni sull’app</h2><p class="long-description">${esc(a.fullDescription||a.description)}</p></section>${a.update?`<section class="panel detail-panel"><h2>Novità e aggiornamenti</h2><span class="badge ${a.updateKind==='Aggiornamento'?'green':'purple'}">${esc(a.updateKind||'Novità')}</span><p class="long-description">${esc(a.update)}</p></section>`:''}<div class="detail-actions">${actions}</div>${!safeURL(a.playUrl)&&!safeURL(a.apkUrl)?'<p class="availability">Il download non è ancora disponibile.</p>':''}<section class="panel detail-panel"><h2>Dettagli</h2><dl class="detail-facts"><div><dt>Versione</dt><dd>${esc(a.version||'—')}</dd></div><div><dt>Categoria</dt><dd>${esc(a.category)}</dd></div><div><dt>Stato</dt><dd>${esc(a.status||'Disponibile')}</dd></div></dl></section>`;
 $('detailContent').querySelectorAll('img').forEach(img=>img.onerror=()=>{img.onerror=null;img.src=EMB.logo});
}
function detailId(){try{return decodeURIComponent(location.hash.slice(5))}catch{return ''}}
function detailRoute(){
 if(history.state?.simplexGuard){history.pushState({simplexInitialized:true,simplexScreen:'home'},'',location.pathname+location.search+'#home');const wasHome=activeScreen==='home';applyScreen('home');if(wasHome)toast('Sei già nella Home');return}
 $('shareDialog').close();$('screenDialog').close();
 if(location.hash.startsWith('#app/')){activeScreen='detail';$('homeView').classList.add('hidden');$('adminView').classList.add('hidden');$('detailView').classList.remove('hidden');setNav('detail');renderDetail(detailId());window.scrollTo({top:history.state?.scroll||0,behavior:'instant'});$('detailTitle')?.focus({preventScroll:true})}
 else{const view=location.hash.slice(1);applyScreen(['home','catalogo','preferiti','admin'].includes(view)?view:'home',history.state||{})}
}
function showDetail(id){snapshotScreen();location.hash='app/'+encodeURIComponent(id)}
let screenGallery=[],screenIndex=0,screenTouchStartX=0;
function updateScreenViewer(){if(!screenGallery.length)return;$('screenImage').src=screenGallery[screenIndex];$('screenCounter').textContent=(screenIndex+1)+' / '+screenGallery.length;$('prevScreen').disabled=screenGallery.length<2;$('nextScreen').disabled=screenGallery.length<2}
function moveScreen(delta){if(screenGallery.length<2)return;screenIndex=(screenIndex+delta+screenGallery.length)%screenGallery.length;updateScreenViewer()}
document.addEventListener('click',e=>{if(e.target.closest('a[href^="#app/"]')){snapshotScreen();detailReturnScroll=window.scrollY;detailInternal=true;}const b=e.target.closest('[data-screen]');if(b){screenGallery=[...$('detailContent').querySelectorAll('[data-screen]')].map(x=>x.dataset.screen);screenIndex=Math.max(0,screenGallery.indexOf(b.dataset.screen));updateScreenViewer();$('screenDialog').showModal()}});
window.addEventListener('popstate',detailRoute);
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#app/')&&!history.state?.simplexInitialized)history.replaceState({simplexInitialized:true,simplexScreen:'detail'},'',location.href);detailRoute()});
$('backDetail').onclick=()=>history.back();
$('closeScreen').onclick=()=>$('screenDialog').close();
$('prevScreen').onclick=e=>{e.stopPropagation();moveScreen(-1)};
$('nextScreen').onclick=e=>{e.stopPropagation();moveScreen(1)};
$('screenDialog').onclick=e=>{if(e.target===$('screenDialog'))$('screenDialog').close()};
$('screenImage').addEventListener('touchstart',e=>{screenTouchStartX=e.changedTouches[0].clientX},{passive:true});
$('screenImage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-screenTouchStartX;if(Math.abs(dx)>45)moveScreen(dx<0?1:-1)},{passive:true});
document.addEventListener('keydown',e=>{if(!$('screenDialog').open)return;if(e.key==='ArrowLeft')moveScreen(-1);if(e.key==='ArrowRight')moveScreen(1)});
function showAdmin(fromHistory=false){if(!fromHistory){navigate('admin');return}activeScreen='admin';$('detailView').classList.add('hidden');checkAdmin();$('homeView').classList.add('hidden');$('adminView').classList.remove('hidden');loadAdmin();setNav('admin');window.scrollTo(0,0)}
function hideAdmin(scroll=true){$('adminView').classList.add('hidden');$('homeView').classList.remove('hidden');if(scroll){setNav('home');render();window.scrollTo(0,0)}}
$('openAdmin').onclick=()=>showAdmin();$('closeAdmin').onclick=()=>history.back();
function loadAdmin(){const s=getSite();$('siteTheme').value=s.theme==='classic'?'classic':'premium';$('sTitle').value=s.title;$('sTag').value=s.tagline;$('sHero').value=s.hero;syncCategorySelect();renderAdminList()}
$('saveSite').onclick=async()=>{try{await adminCall('site',{site:{title:$('sTitle').value.trim()||'SimplexApp',tagline:$('sTag').value.trim(),hero:$('sHero').value.trim(),theme:getSite().theme}});const ok=write(keys.site,{title:$('sTitle').value.trim()||'SimplexApp',tagline:$('sTag').value.trim(),hero:$('sHero').value.trim(),theme:getSite().theme});render();if(ok)toast('Impostazioni pubblicate per tutti')}catch(e){toast(e.message)}};

function shareURL(id){return 'https://meapps-it.github.io/SimplexApp/#app/'+encodeURIComponent(id)}
async function shareApp(id){const a=getApps().find(x=>x.id===id);if(!a)return;const data={title:a.name+' · SimplexApp',text:'Guarda '+a.name+' su SimplexApp. '+(a.description||'Scopri questa app nel catalogo.'),url:shareURL(id)};if(navigator.share){try{const imageUrl=safeIcon(a.icon);if(imageUrl){const r=await fetch(imageUrl);if(r.ok){const blob=await r.blob();const ext=blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png';const file=new File([blob],a.id+'-simplexapp.'+ext,{type:blob.type||'image/png'});const withImage={...data,files:[file]};if(!navigator.canShare||navigator.canShare(withImage)){await navigator.share(withImage);return}}}if(!navigator.canShare||navigator.canShare(data)){await navigator.share(data);return}}catch(e){if(e.name==='AbortError')return}}$('shareName').textContent='Condividi '+a.name;$('shareURL').value=data.url;$('shareDialog').showModal()}
$('closeShare').onclick=()=>$('shareDialog').close();
$('shareDialog').onclick=e=>{if(e.target===$('shareDialog'))$('shareDialog').close()};
$('copyShare').onclick=async()=>{try{await navigator.clipboard.writeText($('shareURL').value);toast('Link copiato');$('shareDialog').close()}catch{$('shareURL').focus();$('shareURL').select();toast('Tieni premuto sul link e scegli Copia')}};
async function publishTheme(theme){try{const result=await adminCall('site',{site:{...getSite(),theme}});write(keys.site,result.site);$('siteTheme').value=theme;render();toast(theme==='classic'?'Grafica Classica ripristinata':'Grafica Blu Premium pubblicata')}catch(e){toast(e.message)}}
$('saveTheme').onclick=()=>publishTheme($('siteTheme').value);
$('restoreClassic').onclick=()=>publishTheme('classic');

function resetForm(){uploadedScreens.clear();['appId','appName','appVersion','appDesc','appFullDesc','appScreens','appScreensFile','appUpdate','appPlay','appApk','appIcon','appIconFile','appApkFile'].forEach(id=>$(id).value='');syncCategorySelect('Produttività');$('appStatus').value='Disponibile';$('appUpdateKind').value='Novità';$('appFeatured').checked=false;$('appPublic').checked=true;editingIcon=''}
function adminSection(settings=false){$('adminAppsPanel').classList.toggle('hidden',settings);$('adminSettingsPanel').classList.toggle('hidden',!settings);for(const [id,active] of [['adminAppsTab',!settings],['adminSettingsTab',settings]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active))}}
function closeEditor(){resetForm();$('appEditor').classList.add('hidden');$('adminDashboard').classList.remove('hidden');$('adminDashboard').scrollIntoView({block:'start'})}
function openEditor(){adminSection();$('adminDashboard').classList.add('hidden');$('appEditor').classList.remove('hidden');$('publishStatus').textContent='';$('editorTitle').textContent=$('appId').value?'Modifica · '+$('appName').value:'Nuova app';$('editorHint').textContent=$('appId').value?'I dati attuali sono già compilati. Cambia solo ciò che ti serve e salva.':'Compila la scheda e pubblicala nel catalogo.';$('saveApp').textContent=$('appId').value?'Salva modifiche':'Pubblica app';renderAdminScreens();$('appEditor').scrollIntoView({block:'start'});$('appName').focus({preventScroll:true})}
function renderAdminScreens(){const urls=$('appScreens').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);$('adminScreensPreview').innerHTML='';urls.forEach((url,index)=>{if(!/^https:\/\//.test(url))return;const item=document.createElement('div');item.innerHTML=`<img src="${esc(url)}" alt="Screenshot ${index+1}" loading="lazy"><button class="secondary" type="button">Rimuovi ${index+1}</button>`;item.querySelector('button').onclick=()=>{urls.splice(index,1);$('appScreens').value=urls.join('\n');renderAdminScreens()};$('adminScreensPreview').appendChild(item)})}
$('appScreens').oninput=renderAdminScreens;
$('newApp').onclick=closeEditor;$('cancelEdit').onclick=closeEditor;$('addApp').onclick=()=>{resetForm();openEditor()};$('addCategory').onclick=async()=>{const name=(prompt('Nome nuova categoria:')||'').trim();if(!name)return;if(name.length>80)return toast('Nome categoria troppo lungo');if(getCategories().some(c=>c.toLocaleLowerCase('it')===name.toLocaleLowerCase('it')))return toast('Categoria già presente');try{const site={...getSite(),categories:[...getCategories(),name]};await adminCall('site',{site});write(keys.site,site);syncCategorySelect(name);toast('Categoria aggiunta')}catch(e){toast(e.message)}};$('renameCategory').onclick=async()=>{const old=$('appCat').value;if(!old)return;const name=(prompt('Nuovo nome per «'+old+'»:',old)||'').trim();if(!name||name===old)return;if(name.length>80)return toast('Nome categoria troppo lungo');if(getCategories().some(c=>c!==old&&c.toLocaleLowerCase('it')===name.toLocaleLowerCase('it')))return toast('Esiste già una categoria con questo nome');try{publishingUI(true);const current=getApps();for(const a of current.filter(a=>a.category===old)){const changed={...a,category:name};await adminCall('save',{app:changed})}const cats=getCategories().map(c=>c===old?name:c);const site={...getSite(),categories:[...new Set(cats)]};await adminCall('site',{site});write(keys.site,site);setApps(current.map(a=>a.category===old?{...a,category:name}:a));syncCategorySelect(name);toast('Categoria modificata')}catch(e){toast(e.message)}finally{publishingUI(false)}};$('adminAppsTab').onclick=()=>adminSection();$('adminSettingsTab').onclick=()=>adminSection(true);$('adminSearch').oninput=renderAdminList;

function editApp(x){if(publishing)return;uploadedScreens.clear();$('appId').value=x.id;$('appName').value=x.name;$('appVersion').value=x.version||'';$('appDesc').value=x.description||'';$('appFullDesc').value=x.fullDescription||'';$('appScreens').value=(x.screenshots||[]).join('\n');$('appScreensFile').value='';syncCategorySelect(x.category||'Utility');$('appStatus').value=x.status||'Disponibile';$('appUpdate').value=x.update||'';$('appUpdateKind').value=x.updateKind||'Novità';$('appPlay').value=x.playUrl||'';$('appApk').value=x.apkUrl||'';editingIcon=x.icon||EMB.logo;$('appIcon').value=(x.icon||'').startsWith('data:')?'':x.icon||'';$('appIconFile').value='';$('appApkFile').value='';$('appFeatured').checked=!!x.featured;$('appPublic').checked=x.visiblePublic!==false;openEditor()}
async function imageFile(file,maxDimension=256){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Usa PNG, JPEG, WebP o GIF.');if(file.size>8*1024*1024)throw Error('Immagine troppo grande (massimo 8 MB).');const bitmap=await createImageBitmap(file);const size=Math.min(1,maxDimension/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*size);canvas.height=Math.round(bitmap.height*size);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/png')}
let publishing=false;const uploadedScreens=new Map();
function publishingUI(active){publishing=active;$('adminControls').querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=active);$('uploadProgress').classList.toggle('hidden',!active);$('saveApp').textContent=active?'Pubblicazione…':($('appId').value?'Salva modifiche':'Pubblica app')}
$('saveApp').onclick=async()=>{if(publishing)return;if(!$('appName').value.trim())return toast('Inserisci il nome dell’app');for(const id of ['appPlay','appApk'])if($(id).value.trim()&&!/^https:\/\//.test($(id).value.trim()))return toast('Inserisci link HTTPS validi');const file=$('appApkFile').files[0];if(file&&(!/\.apk$/i.test(file.name)||file.size>=2*1024*1024*1024))return toast('Seleziona una APK inferiore a 2 GiB');if(file&&!$('appVersion').value.trim())return toast('Inserisci la versione dell’APK');const item={id:$('appId').value||'app_'+Date.now(),name:$('appName').value.trim(),version:$('appVersion').value.trim(),description:$('appDesc').value.trim(),fullDescription:$('appFullDesc').value.trim(),screenshots:$('appScreens').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),category:$('appCat').value,status:$('appStatus').value,update:$('appUpdate').value.trim(),updateKind:$('appUpdateKind').value,playUrl:$('appPlay').value.trim(),apkUrl:$('appApk').value.trim(),icon:$('appIcon').value.trim()||editingIcon||new URL(EMB.logo,location.href).href,featured:$('appFeatured').checked,visiblePublic:$('appPublic').checked};if(item.screenshots.length+Array.from($('appScreensFile').files).filter(f=>!uploadedScreens.has(f)).length>12)return toast('Puoi inserire al massimo 12 screenshot');if(item.screenshots.some(u=>!/^https:\/\//.test(u)))return toast('Usa link HTTPS per gli screenshot');try{publishingUI(true);$('publishStatus').textContent='Pubblicazione in corso…';if($('appIconFile').files[0]){const png=await (await fetch(await imageFile($('appIconFile').files[0]))).blob();item.icon=(await uploadFile('icon',png)).url;$('appIcon').value=item.icon;editingIcon=item.icon}item.icon=new URL(item.icon,location.href).href;for(const screenshot of Array.from($('appScreensFile').files)){if(uploadedScreens.has(screenshot))continue;const png=await(await fetch(await imageFile(screenshot,1600))).blob();const uploaded=(await uploadFile('icon',png)).url;uploadedScreens.set(screenshot,uploaded);item.screenshots.push(uploaded);$('appScreens').value=item.screenshots.join('\n')}$('appScreensFile').value='';uploadedScreens.clear();if(file){item.apkUrl=(await uploadFile('apk',file,{id:item.id,version:item.version})).url;$('appApk').value=item.apkUrl;$('appApkFile').value='';$('appId').value=item.id}const published=await adminCall('save',{app:item});const current=getApps();const idx=current.findIndex(a=>a.id===item.id);if(idx<0)current.push(published.app);else current[idx]=published.app;setApps(current);await refreshAdminApps().catch(()=>{});closeEditor();$('adminNotice').textContent=item.visiblePublic?item.name+' · pubblicata nel sito pubblico.':item.name+' · salvata solo per l’Admin.';toast(item.visiblePublic?'App pubblicata per tutti':'App visibile solo all’Admin')}catch(e){$('publishStatus').textContent=e.message;toast(e.message)}finally{publishingUI(false)}};
function renderAdminList(){const list=$('adminList');list.innerHTML='';$('adminCount').textContent='('+getApps().length+')';const term=$('adminSearch').value.trim().toLowerCase();const apps=getApps().filter(x=>x.name.toLowerCase().includes(term));if(!apps.length)list.innerHTML='<p class=note>Nessuna app trovata.</p>';apps.forEach(x=>{const d=document.createElement('div');d.className='admin-item';d.innerHTML=`<img class=admin-app-icon src="${esc(safeIcon(x.icon))}" alt=""><div class=admin-app-info><strong>${esc(x.name)}</strong><small>${esc(x.category)} · ${esc(x.status)} · v${esc(x.version)}${x.visiblePublic===false?' · SOLO ADMIN':''}</small></div><div><button class="primary e">✎ Modifica</button> <button class="danger d">Elimina</button></div>`;d.querySelector('.e').onclick=()=>editApp(x);d.querySelector('.d').onclick=async()=>{if(publishing)return;if(confirm('Eliminare '+x.name+' dal catalogo pubblico? Le APK già pubblicate restano nelle Releases.')){try{await adminCall('delete',{id:x.id});await refreshAdminApps();write(keys.favs,getFavs().filter(id=>id!==x.id));toast('App eliminata dal catalogo')}catch(e){toast(e.message)}}};list.appendChild(d)})}
$('exportData').onclick=()=>{const data={schemaVersion:1,site:getSite(),apps:getApps()};const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.download='simplex-catalogo.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),5000)};
function normalizeApps(a){if(!Array.isArray(a))throw Error('Il catalogo deve contenere un elenco di app.');const ids=new Set();return a.map(x=>{if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.name!=='string'||!x.name.trim())throw Error('Scheda non valida o ID duplicato.');ids.add(x.id);const y={id:x.id,name:x.name,featured:!!x.featured,visiblePublic:x.visiblePublic!==false,fullDescription:typeof x.fullDescription==='string'?x.fullDescription:'',screenshots:Array.isArray(x.screenshots)?x.screenshots.filter(u=>typeof u==='string').slice(0,12):[]};for(const k of ['version','description','status','update','updateKind','playUrl','apkUrl','icon'])y[k]=typeof x[k]==='string'?x[k]:'';y.category=typeof x.category==='string'&&x.category.trim()?x.category.trim().slice(0,80):'Utility';return y})}
$('importData').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());const apps=normalizeApps(Array.isArray(data)?data:data.apps);if(!confirm('Pubblicare e sostituire il catalogo online con '+apps.length+' app?'))return;publishingUI(true);for(const a of apps){if(a.icon.startsWith('data:image/'))a.icon=(await uploadFile('icon',await(await fetch(a.icon)).blob())).url;else a.icon=new URL(a.icon||EMB.logo,location.href).href}await adminCall('import',{apps,site:data.site||getSite()});await refreshAdminApps();loadAdmin();toast('Catalogo importato')}catch(err){toast('Importazione fallita: '+err.message)}finally{publishingUI(false);e.target.value=''}};
async function refreshCloud(){const data=await loadCloud();write(keys.apps,normalizeApps(data.apps));if(data.site)write(keys.site,data.site);render();renderAdminList();if(location.hash.startsWith('#app/'))renderDetail(detailId())}
async function refreshAdminApps(){const data=await adminCall('list');write(keys.apps,normalizeApps(data.apps||[]));render();renderAdminList()}
let checkingAdmin=null;
async function checkAdmin(){if(checkingAdmin)return checkingAdmin;checkingAdmin=(async()=>{if(!adminSession){$('adminControls').classList.add('hidden');$('adminRestore').classList.add('hidden');$('adminLogin').classList.remove('hidden');return false}const alreadyOpen=!$('adminControls').classList.contains('hidden');$('adminLogin').classList.add('hidden');if(!alreadyOpen)$('adminRestore').classList.remove('hidden');$('retryAdmin').classList.add('hidden');try{const status=await adminCall('status');$('adminControls').classList.remove('hidden');$('adminRestore').classList.add('hidden');$('connectionStatus').textContent='Connesso come '+status.email+' · '+(status.githubConnected?'Caricamento APK pronto':'Collega GitHub per caricare le APK');await refreshAdminApps();return true}catch(e){if(!adminSession||[401,403].includes(e.status)){$('adminControls').classList.add('hidden');$('adminRestore').classList.add('hidden');$('adminLogin').classList.remove('hidden');$('loginStatus').textContent=e.message}else{$('restoreStatus').textContent='Accesso conservato. '+e.message;$('adminRestore').classList.remove('hidden');$('retryAdmin').classList.remove('hidden')}return false}})().finally(()=>checkingAdmin=null);return checkingAdmin}
$('retryAdmin').onclick=()=>checkAdmin();
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;$('loginStatus').textContent='Accesso in corso…';try{const s=await cloudFetch('/auth/v1/token?grant_type=password',{method:'POST',body:{email:$('adminEmail').value.trim(),password:$('adminPassword').value}});rememberSession({...s,expires_at:Math.floor(Date.now()/1000)+s.expires_in});$('adminPassword').value='';if(await checkAdmin()){await refreshCloud();loadAdmin()}}catch(err){$('loginStatus').textContent=err.message==='Invalid login credentials'?'Email o password non corretta. Usa il tuo account Supabase esistente.':err.message}finally{$('loginButton').disabled=false}};
$('logoutAdmin').onclick=async()=>{try{await cloudFetch('/auth/v1/logout',{method:'POST',token:await accessToken()})}catch{}rememberSession(null);await checkAdmin();toast('Accesso Admin chiuso')};
$('connectGithub').onclick=async()=>{const token=$('githubToken').value.trim();$('githubToken').value='';try{await adminCall('connect',{token});await checkAdmin();toast('GitHub collegato: puoi caricare le APK')}catch(e){toast(e.message)}};
$('disconnectGithub').onclick=async()=>{if(!confirm('Scollegare il caricamento APK? Il catalogo e le APK pubblicate rimangono disponibili.'))return;try{await adminCall('disconnect');await checkAdmin();toast('GitHub scollegato')}catch(e){toast(e.message)}};
window.addEventListener('beforeunload',e=>{if(publishing){e.preventDefault();e.returnValue=''}});
async function boot(){if(adminSession)accessToken().catch(()=>{});try{await refreshCloud()}catch{toast('Catalogo offline: mostro l’ultima copia disponibile.')}if('serviceWorker'in navigator&&['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>toast('Modalità offline non disponibile su questo indirizzo'))}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('adminView').classList.contains('hidden'))refreshCloud().catch(()=>{})});
setInterval(()=>{if(!document.hidden&&$('adminView').classList.contains('hidden'))refreshCloud().catch(()=>{})},60000);
// A Home sentinel keeps Android Back inside the PWA at the root screen.
if(!history.state?.simplexInitialized){const start=location.hash||'#home';history.replaceState({simplexGuard:true},'',location.pathname+location.search+'#home');history.pushState({simplexInitialized:true,simplexScreen:start.startsWith('#app/')?'detail':start.slice(1)},'',location.pathname+location.search+start)}
render();detailRoute();boot();
