'use strict';
const CLOUD={url:'https://qfjwtawsqfwmsmrrgqfi.supabase.co',key:'sb_publishable_-EUVjwsk3txKk2Opqrc7Kw_xFNa9Hw1'};
let adminSession=null;
try{adminSession=JSON.parse(localStorage.getItem('simplex_admin_session')||sessionStorage.getItem('simplex_admin_session'));if(adminSession)localStorage.setItem('simplex_admin_session',JSON.stringify(adminSession));sessionStorage.removeItem('simplex_admin_session')}catch{}
function rememberSession(s){adminSession=s;try{if(s)localStorage.setItem('simplex_admin_session',JSON.stringify(s));else localStorage.removeItem('simplex_admin_session');sessionStorage.removeItem('simplex_admin_session')}catch{}}
async function cloudFetch(path,{method='GET',body,token,headers={}}={}){const r=await fetch(CLOUD.url+path,{method,cache:'no-store',headers:{apikey:CLOUD.key,...(token?{Authorization:'Bearer '+token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const error=Error(d.error_description||d.msg||d.error?.message||d.error||d.message||'Connessione non riuscita');error.status=r.status;throw error;}return d}
let refreshingSession=null;
async function refreshSession(){if(!refreshingSession)refreshingSession=cloudFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:adminSession.refresh_token}}).finally(()=>{refreshingSession=null});return refreshingSession}
window.addEventListener('storage',e=>{if(e.key==='simplex_admin_session'){try{adminSession=JSON.parse(e.newValue)}catch{adminSession=null}}});
async function accessToken(){if(!adminSession)throw Error('Accedi all’Admin');if(adminSession.expires_at*1000<Date.now()+60000){try{const s=await refreshSession();rememberSession({...s,expires_at:Math.floor(Date.now()/1000)+s.expires_in})}catch(e){if([400,401,403].includes(e.status)){rememberSession(null);throw Error('Sessione scaduta: accedi di nuovo')}throw Error('Connessione assente: riprova senza uscire dall’Admin')}}return adminSession.access_token}
async function adminCall(action,body){return cloudFetch('/functions/v1/simplex-admin?action='+action,{method:'POST',body:body??{},token:await accessToken()})}
async function loadCloud(){const [a,s]=await Promise.all([cloudFetch('/rest/v1/simplex_apps?select=payload&order=id'),cloudFetch('/rest/v1/simplex_site?id=eq.1&select=payload')]);const rank={toi:0,spesa:1,vg:2};return {apps:a.map(x=>x.payload).sort((x,y)=>(rank[x.id]??100)-(rank[y.id]??100)),site:s[0]?.payload}}
async function uploadFile(action,file,args={}){const token=await accessToken();return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();const query=new URLSearchParams({action,...args});xhr.open('POST',CLOUD.url+'/functions/v1/simplex-admin?'+query);xhr.setRequestHeader('apikey',CLOUD.key);xhr.setRequestHeader('Authorization','Bearer '+token);xhr.setRequestHeader('Content-Type',action==='apk'?'application/vnd.android.package-archive':'image/png');xhr.setRequestHeader('x-file-size',String(file.size));xhr.timeout=300000;xhr.upload.onprogress=e=>{if(e.lengthComputable){const percent=Math.round(e.loaded/e.total*100);document.getElementById('uploadProgress').value=percent;document.getElementById('publishStatus').textContent=percent<100?'Caricamento '+percent+'%…':'Caricamento ricevuto, attendo conferma…'}};xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(Error(xhr.status===504?'Caricamento troppo lento: riprova con una connessione più veloce.':'Risposta del server non valida'));return}if(xhr.status<200||xhr.status>=300)reject(Error(data.error||'Caricamento non riuscito'));else resolve(data)};xhr.onerror=()=>reject(Error('Connessione interrotta. Il catalogo non è stato pubblicato. Riprova.'));xhr.ontimeout=()=>reject(Error('Caricamento troppo lento o file troppo grande per la connessione. Riprova con una rete più veloce.'));xhr.send(file)})}
