'use strict';
const PROMO_DEFAULTS={
 toi:{promoImages:['assets/promotional/turni-operai.png']},
 app_1790955596835:{promoImages:['assets/promotional/noidue.jpg']}
};
const uploadedPromo=new Map();
function promoURLs(app,key){const values=Array.isArray(app[key])?app[key]:(PROMO_DEFAULTS[app.id]?.[key]||[]);return values.map(u=>{try{const url=new URL(u,location.href);return url.protocol==='https:'&&!url.username&&!url.password?url.href:''}catch{return ''}}).filter(Boolean).slice(0,6)}
function renderPromo(app){const images=promoURLs(app,'promoImages');if(!images.length)return '';return `<section class="panel detail-panel"><h2>Immagini da condividere</h2><p class="note">Scarica un’immagine o condividila scegliendo un’app dal menu del telefono.</p><div class="promo-gallery">${images.map((url,index)=>`<article class="promo-card"><a href="${esc(url)}" target="_blank" rel="noopener noreferrer" aria-label="Apri immagine promozionale ${index+1}"><img src="${esc(url)}" alt="Immagine promozionale ${index+1} di ${esc(app.name)}" loading="lazy"></a><p>Immagine promozionale ${index+1}</p><div class="promo-actions"><button class="secondary" data-promo-download="${index}" data-promo-app="${esc(app.id)}">Scarica immagine</button><button class="primary" data-promo-share="${index}" data-promo-app="${esc(app.id)}">Condividi immagine</button></div></article>`).join('')}</div></section>`}
function downloadPromo(file){const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function handlePromo(button){if(button.disabled)return;const app=getApps().find(a=>a.id===button.dataset.promoApp);if(!app)return;const index=Number(button.dataset.promoShare??button.dataset.promoDownload),url=promoURLs(app,'promoImages')[index];if(!url)return;const label=button.textContent;button.disabled=true;button.textContent='Preparo il file…';try{const response=await fetch(url);if(!response.ok)throw Error();const blob=await response.blob();if(blob.size>25*1024*1024)throw Error();const type=blob.type.split(';')[0];if(!['image/png','image/jpeg','image/webp'].includes(type))throw Error();const extension=type==='image/jpeg'?'jpg':type==='image/webp'?'webp':'png',file=new File([blob],app.id+'-social-'+(index+1)+'.'+extension,{type});const data={files:[file]};if(button.dataset.promoShare!==undefined&&navigator.share&&navigator.canShare?.(data)){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}downloadPromo(file);toast(button.dataset.promoShare!==undefined?'File scaricato: puoi aggiungerlo al post.':'Download avviato')}catch{toast('File non disponibile. Controlla la connessione e riprova.')}finally{button.disabled=false;button.textContent=label}}
function mediaLines(id){return $(id).value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)}
function validatePromoForm(item){const pending=Array.from($('appPromoImagesFile').files).filter(f=>!uploadedPromo.has(f));if(item.promoImages.length+pending.length>6)throw Error('Puoi aggiungere al massimo 6 immagini promozionali');for(const u of item.promoImages){const parsed=new URL(u);if(parsed.protocol!=='https:'||parsed.username||parsed.password||u.length>3000)throw Error('Usa link HTTPS per le immagini promozionali')}for(const f of pending)if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024)throw Error('Usa immagini PNG, JPEG o WebP di massimo 8 MB')}
async function uploadPromo(item){for(const file of Array.from($('appPromoImagesFile').files)){if(uploadedPromo.has(file))continue;const blob=await(await fetch(await imageFile(file,1920))).blob();const result=await uploadFile('icon',blob);uploadedPromo.set(file,result.url);item.promoImages.push(result.url);$('appPromoImages').value=item.promoImages.join('\n')}$('appPromoImagesFile').value='';uploadedPromo.clear()}
