'use strict';
let productModuleCatalog=new Map();
let managedProducts=new Set(),serverModuleCustomers=[],serverModulesProduct='',serverModulesRequest=0;
function hasServerModules(id){return managedProducts.has(id)}
function modulesForProduct(id){return productModuleCatalog.get(id)||[]}
function activeProductModules(product,values){return modulesForProduct(product).filter(m=>m.ready!==false&&values?.[m.key]===true)}
async function loadProductModules(){productModuleCatalog.clear();managedProducts.clear();const r=await adminCall('product-modules');for(const row of r.products||[]){productModuleCatalog.set(row.product_id,row.modules||[]);if(row.managed)managedProducts.add(row.product_id)}}
function clearProductModules(){productModuleCatalog.clear();managedProducts.clear();serverModuleCustomers=[];serverModulesProduct='';serverModulesRequest++;document.querySelectorAll('[data-server-module]').forEach(x=>x.remove())}
function productModuleInputs(product,values={}){const modules=modulesForProduct(product);return modules.length?modules.map(m=>`<label><input class="client-module" data-module="${esc(m.key)}" type="checkbox" ${m.ready===false?'disabled':values[m.key]===true?'checked':''}> ${esc(m.label)}${m.ready===false?' · In sviluppo':''}</label>`).join(''):'<p class="note">'+(product?'Moduli non ancora configurati per questa applicazione.':'Scegli prima un’applicazione.')+'</p>'}
function productModuleBadges(product,values){return activeProductModules(product,values).map(m=>`<span>${esc(m.label)}</span>`).join('')}
async function loadServerModules(product,force=false){
 if(serverModulesProduct===product&&!force)return;
 const request=++serverModulesRequest;serverModulesProduct=product;serverModuleCustomers=[];$('serverModuleGrid').innerHTML='';$('saveProductModules').disabled=true;$('serverModuleStatus').textContent='Caricamento clienti della versione completa…';
 try{const response=await adminCall('product-customers',{id:product});if(request!==serverModulesRequest||$('moduleProductSelect').value!==product)return;serverModuleCustomers=response.customers||[];const select=$('serverModuleCustomerSelect');select.innerHTML='<option value="">Scegli un cliente</option>'+serverModuleCustomers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.active===false?' · Sospeso':''}</option>`).join('');if(serverModuleCustomers.length===1)select.value=serverModuleCustomers[0].id;$('serverModuleStatus').textContent=serverModuleCustomers.length?'':'Nessun cliente della versione completa configurato.';renderServerModuleSelection();}
 catch(e){if(request===serverModulesRequest){serverModulesProduct='';$('serverModuleCustomerSelect').innerHTML='<option value="">Caricamento non riuscito</option>';$('serverModuleStatus').textContent=e.message}}
}
function renderServerModuleSelection(){const c=serverModuleCustomers.find(x=>x.id===$('serverModuleCustomerSelect').value),product=$('moduleProductSelect').value;$('saveProductModules').disabled=!c;$('serverModuleGrid').innerHTML=c?modulesForProduct(product).map(m=>`<label><input data-server-module="${esc(m.key)}" type="checkbox" ${m.ready===false?'disabled':c.modules?.[m.key]===true?'checked':''}> ${esc(m.label)}${m.ready===false?' · In sviluppo':''}</label>`).join(''):''}
async function saveServerModules(){const product=$('moduleProductSelect').value,customer=$('serverModuleCustomerSelect').value;if(!hasServerModules(product)||!serverModuleCustomers.some(c=>c.id===customer))return;const modules={};$('serverModuleGrid').querySelectorAll('[data-server-module]').forEach(x=>{if(!x.disabled)modules[x.dataset.serverModule]=x.checked});$('saveProductModules').disabled=true;$('serverModuleStatus').textContent='Salvataggio sul server…';try{const response=await adminCall('product-customer-modules',{id:product,customerId:customer,modules});if(!response.saved)throw Error('Salvataggio non confermato');const c=serverModuleCustomers.find(x=>x.id===customer);if(c)c.modules=response.modules;if($('moduleProductSelect').value===product)$('serverModuleStatus').textContent='Moduli salvati. Nella versione completa premi Sincronizza per aggiornare i permessi.';}catch(e){$('serverModuleStatus').textContent=e.message}finally{if($('moduleProductSelect').value===product)$('saveProductModules').disabled=false}}
