'use strict';
function onlineURL(value){if(typeof value!=='string'||value.length>3000)return '';try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:''}catch{return ''}}
function productLabels(app){const labels=[];if(onlineURL(app.webUrl))labels.push('Online');if(safeURL(app.apkUrl)||safeURL(app.playUrl))labels.push('Android');if(app.customizable===true)labels.push('Personalizzabile');return labels.map(label=>`<span class="version">${label}</span>`).join('')}
function onlineActions(app){return `${onlineURL(app.webUrl)?`<a class="btn" href="${esc(onlineURL(app.webUrl))}" target="_blank" rel="noopener noreferrer">Apri</a>`:''}${onlineURL(app.demoUrl)?`<a class="secondary btn" href="${esc(onlineURL(app.demoUrl))}" target="_blank" rel="noopener noreferrer">Apri demo</a>`:''}${privateProductAction(app.id)}${app.customizable===true?`<button class="secondary" data-customize="${esc(app.id)}">Richiedi personalizzazione</button>`:''}`}
function requestCustomization(id){const app=getPublicApps().find(a=>a.id===id);if(!app||app.customizable!==true)return;navigate('home',{scroll:0});$('contactProduct').value=app.name;$('contactTopic').value='Personalizzazione';requestAnimationFrame(()=>{$('contatti').scrollIntoView({behavior:'smooth',block:'start'});$('contactTitle').focus({preventScroll:true})})}
// Memory only. The server checks authenticated admin membership before returning links.
let privateProductLinks=new Map();
async function loadPrivateProductLinks(){privateProductLinks.clear();const r=await adminCall('product-links');for(const x of r.links||[]){const url=onlineURL(x.full_url);if(url)privateProductLinks.set(x.product_id,url)}}
function clearPrivateProductLinks(){privateProductLinks.clear();document.querySelectorAll('[data-private-product]').forEach(el=>el.remove())}
function privateProductAction(id){const url=privateProductLinks.get(id);return url?`<a class="secondary btn" data-private-product="${esc(id)}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Apri versione completa</a>`:''}
