import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
let fetched=[];
const context=vm.createContext({location:{href:'https://meapps-it.github.io/SimplexApp/'},URL,Map,File,safeIcon:u=>u||'',fetch:async url=>{fetched.push(url);return new Response(new Uint8Array([1,2]),{headers:{'Content-Type':'image/png'}})}});
vm.runInContext(readFileSync(new URL('../media.js',import.meta.url),'utf8'),context);
assert.equal(vm.runInContext("shareImageURL({id:'toi'})",context),'https://meapps-it.github.io/SimplexApp/assets/promotional/turni-operai.png');
assert.equal(vm.runInContext("shareImageURL({id:'toi',promoImages:[],icon:'icon.png'})",context),'icon.png');
assert.equal(vm.runInContext("promoURLs({id:'a',promoImages:['javascript:alert(1)','https://user:pass@example.test/a','http://example.test/a']},'promoImages').length",context),0);
const app={id:'test',promoImages:['https://example.test/old.png','https://example.test/latest.png'],icon:'icon.png'};
const file=await context.prepareShareImage(app);assert.equal(file.type,'image/png');assert.deepEqual(fetched,['https://example.test/latest.png']);
assert.equal(await context.prepareShareImage(app),file);assert.equal(fetched.length,1);
app.promoImages.push('https://example.test/new.png');await context.prepareShareImage(app);assert.equal(fetched.at(-1),'https://example.test/new.png');
context.fetch=async()=>new Response('wrong',{headers:{'Content-Type':'text/html'}});
assert.equal(await context.prepareShareImage({id:'bad',promoImages:['https://example.test/bad']}),null);
context.fetch=async()=>{throw Error('offline')};assert.equal(await context.prepareShareImage({id:'offline',promoImages:['https://example.test/offline']}),null);
const appSource=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.ok(!appSource.includes('renderPromo('));assert.ok(!appSource.includes('handlePromo('));assert.ok(appSource.includes('assets/google-play-badge-it.png'));assert.ok(appSource.includes('Scarica dal Play Store'));
console.log('PASS: latest promotional image, default assets, explicit removal, safe URLs, preload cache, changed image, invalid MIME/offline and no public image gallery.');
