import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
let shared,downloads=0,toasts=[];
const app={id:'test',name:'Test',promoImages:['https://example.test/image.png']};
const context=vm.createContext({location:{href:'https://meapps-it.github.io/SimplexApp/'},URL,Map,File,setTimeout:()=>{},getApps:()=>[app],esc:s=>String(s).replaceAll('"','&quot;'),toast:s=>toasts.push(s),navigator:{canShare:()=>true,share:async data=>shared=data},fetch:async()=>new Response(new Uint8Array([1,2]),{headers:{'Content-Type':'image/png'}})});
vm.runInContext(readFileSync(new URL('../media.js',import.meta.url),'utf8'),context);
assert.equal(vm.runInContext("promoURLs({id:'toi'},'promoImages')[0]",context),'https://meapps-it.github.io/SimplexApp/assets/promotional/turni-operai.png');
assert.equal(vm.runInContext("promoURLs({id:'toi',promoImages:[]},'promoImages').length",context),0);
assert.equal(vm.runInContext("promoURLs({id:'a',promoImages:['javascript:alert(1)','https://user:pass@example.test/a','http://example.test/a']},'promoImages').length",context),0);
assert.ok(vm.runInContext("renderPromo({id:'toi',name:'Test'})",context).includes('loading="lazy"'));
assert.equal(vm.runInContext("renderPromo({id:'unknown',name:'Test'})",context),'');
vm.runInContext('downloadPromo=()=>{downloadCount++}',context);context.downloadCount=0;
const button={dataset:{promoShare:'0',promoKind:'promoImages',promoApp:'test'},textContent:'Condividi',disabled:false};
await context.handlePromo(button);assert.equal(shared.files[0].type,'image/png');assert.equal(shared.url,undefined);assert.equal(button.disabled,false);
context.navigator.share=async()=>{throw Object.assign(Error(),{name:'AbortError'})};await context.handlePromo(button);assert.equal(context.downloadCount,0);
context.navigator.canShare=()=>false;await context.handlePromo(button);assert.equal(context.downloadCount,1);
context.fetch=async()=>new Response('wrong',{headers:{'Content-Type':'text/html'}});await context.handlePromo(button);assert.equal(context.downloadCount,1);assert.ok(toasts.at(-1).includes('non disponibile'));
console.log('PASS: promotional defaults, explicit removal, safe URLs, lazy images, file sharing, cancellation, download fallback and invalid MIME rejection.');
