import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
test('Admin preview follows the selected PWA and never keeps another client branding',async()=>{
 const dom=new JSDOM(await readFile('index.html','utf8'),{url:'https://example.com/',runScripts:'outside-only'}),w=dom.window;
 w.getApps=()=>[{id:'inventory',name:'Gestionale & Inventario',icon:'https://example.com/icon.png'},{id:'other',name:'Altra PWA'}];const defs=[{key:'products',label:'Articoli',ready:true},{key:'inventory',label:'Magazzino',ready:true,requires:['products']}];w.modulesForProduct=id=>id==='inventory'?defs:[];w.readClientModules=()=>Object.fromEntries([...w.document.querySelectorAll('.client-module')].map(el=>[el.dataset.module,el.checked]));w.updateModuleCount=()=>{};
 w.eval(await readFile('tenant-config.js','utf8'));w.eval(await readFile('tenant-customization.js','utf8'));const editor=w.tenantCustomization,T=w.SimplexTenants;
 editor.setProfiles([{product_id:'inventory',capabilities:{version:2,fields:T.fields,menu_layouts:T.layouts,themes:Object.keys(T.presets),defaults:{app_name:'Originale',primary_color:'#0c2d50'}}},{product_id:'other',capabilities:{version:2,fields:['app_name'],menu_layouts:['original']}}]);
 const product=w.document.getElementById('clientProduct');product.innerHTML='<option value="inventory">Inventario</option><option value="other">Altra PWA</option>';product.value='inventory';w.document.getElementById('clientModuleGrid').innerHTML='<label><input type="checkbox" class="client-module" data-module="products" checked>Articoli</label><label><input type="checkbox" class="client-module" data-module="inventory" checked>Magazzino</label>';
 const a={business_name:'Ferramenta Rossi',email:'rossi@example.com',plan:'base',branding:{app_name:'Gestionale Rossi',primary_color:'#a52c35',logo_url:'https://example.com/rossi.png',menu_layout:'left'}};editor.open(a);assert.match(w.document.getElementById('tenantPreview').textContent,/Gestionale Rossi/);assert.equal(editor.read().branding.primary_color,'#a52c35');assert.equal(w.document.querySelector('.tenant-asset-preview').src,a.branding.logo_url);
 const b={business_name:'Bianchi',email:'bianchi@example.com',plan:'premium',branding:{app_name:'Bianchi',primary_color:'#174a8b',menu_layout:'right'}};editor.open(b);assert.equal(editor.read().branding.app_name,'Bianchi');assert.equal(editor.read().branding.logo_url,undefined);assert.equal(w.document.getElementById('tenantPreview').dataset.layout,'right');assert.equal(a.branding.logo_url,'https://example.com/rossi.png');
 w.document.getElementById('tenantRestore').click();assert.deepEqual(JSON.parse(JSON.stringify(editor.read().branding)),{});assert.match(w.document.getElementById('tenantPreview').textContent,/Originale/);
 product.value='other';editor.productChanged();assert.equal(w.document.querySelectorAll('[data-branding]').length,1);assert.equal(w.document.querySelector('[data-branding]').dataset.branding,'app_name');assert.equal(w.document.getElementById('tenantPreset').disabled,true);
 dom.window.close();
});
